name: superbank
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_core_platform_interface: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_database: ^12.0.0
  firebase_auth: ^6.0.0
  firebase_auth_web: ^6.0.0 # Added for web support
  cloud_firestore: ^6.0.0
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  google_sign_in: ^7.1.1
  shared_preferences: ^2.1.1
  flutter_facebook_auth: ^7.1.2
  cupertino_icons: ^1.0.5
  cloud_functions: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

  assets:
    - assets/images/
