// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQs7v9FNZ_FMBQVH5FYHAGXjDK9e95dwY',
    appId: '1:698853456796:web:522529b1fb7d8324762659',
    messagingSenderId: '698853456796',
    projectId: 'superbank-20',
    authDomain: 'superbank-20.firebaseapp.com',
    storageBucket: 'superbank-20.firebasestorage.app',
    measurementId: 'G-KW6PGR7JMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSza0qZdaih7k8DQbJQnP-_Oi79nXKL2Y',
    appId: '1:698853456796:android:2fa2cb92bfd3ed01762659',
    messagingSenderId: '698853456796',
    projectId: 'superbank-20',
    storageBucket: 'superbank-20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa47Z9Sa4JL_cwBmnZWpJFcevpe3CXMeo',
    appId: '1:698853456796:ios:7fdbfbe238b30837762659',
    messagingSenderId: '698853456796',
    projectId: 'superbank-20',
    storageBucket: 'superbank-20.firebasestorage.app',
    iosBundleId: 'com.example.superbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa47Z9Sa4JL_cwBmnZWpJFcevpe3CXMeo',
    appId: '1:698853456796:ios:7fdbfbe238b30837762659',
    messagingSenderId: '698853456796',
    projectId: 'superbank-20',
    storageBucket: 'superbank-20.firebasestorage.app',
    iosBundleId: 'com.example.superbank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQs7v9FNZ_FMBQVH5FYHAGXjDK9e95dwY',
    appId: '1:698853456796:web:946fb26069b4088b762659',
    messagingSenderId: '698853456796',
    projectId: 'superbank-20',
    authDomain: 'superbank-20.firebaseapp.com',
    storageBucket: 'superbank-20.firebasestorage.app',
    measurementId: 'G-DDFQ3RW1RK',
  );
}
